spring:
  application:
    name: spribe
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

